<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>mac</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <!-- THIS IS A MAC-ONLY TOOL -->
        <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
        <SupportedOSPlatform>macos</SupportedOSPlatform>
        <NoWarn>$(NoWarn);CA1416</NoWarn>
        <DebugType>none</DebugType>
        <Version>0.2.0</Version>
    </PropertyGroup>

</Project>
